// <auto-generated />
using System;
using FoodCatalog.Api.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodCatalog.Api.Migrations
{
    [DbContext(typeof(FoodCatalogDbContext))]
    [Migration("20250423204515_Add nutrient seeding")]
    partial class Addnutrientseeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoodCatalog.Api.Models.Domain.Food", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MealId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("FoodCatalog.Api.Models.Domain.FoodMeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MeasureId")
                        .HasColumnType("uuid");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("MeasureId");

                    b.ToTable("FoodMeals");
                });

            modelBuilder.Entity("FoodCatalog.Api.Models.Domain.FoodNutrientIn100g", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("NutrientId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("NutrientId");

                    b.ToTable("FoodNutrientIn100Gs");
                });

            modelBuilder.Entity("FoodCatalog.Api.Models.Domain.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("FoodCatalog.Api.Models.Domain.Measure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WeightInGrams")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.ToTable("Measures");
                });

            modelBuilder.Entity("FoodCatalog.Api.Models.Domain.Nutrient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Nutrients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("92904bea-e00f-48ae-9403-488b0f7b3bdb"),
                            IsDeleted = false,
                            Name = "Calcium, Ca",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("09ec2628-6c48-42ac-b3c7-a6ce53a4686c"),
                            IsDeleted = false,
                            Name = "Carbohydrate, by difference",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("af9575b8-8158-46b0-8980-2bb3b03df6e9"),
                            IsDeleted = false,
                            Name = "Cholesterol",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("0fd0c57b-2b41-40a5-9c57-11085f19838c"),
                            IsDeleted = false,
                            Name = "Energy",
                            Unit = "kcal"
                        },
                        new
                        {
                            Id = new Guid("0f3cfcbf-1eb2-411c-aec9-a779bced180c"),
                            IsDeleted = false,
                            Name = "Fatty acids, total saturated",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("66db2a18-bcff-4797-ae0d-65a8a3bc41a1"),
                            IsDeleted = false,
                            Name = "Total fat",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("285681ee-6908-4887-9034-34dc2aab51d4"),
                            IsDeleted = false,
                            Name = "Fatty acids, total trans",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("42e2a0b2-cbbc-4f7c-a6a4-3bd73c53412f"),
                            IsDeleted = false,
                            Name = "Iron, Fe",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("c5ea852b-65b3-43be-8b31-ab0bbabe6814"),
                            IsDeleted = false,
                            Name = "Fiber, total dietary",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("82277d5b-19e9-4f3c-b2a5-2a7a001682bb"),
                            IsDeleted = false,
                            Name = "Potassium, K",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("2c30679f-bf99-469c-9035-f9a973148b57"),
                            IsDeleted = false,
                            Name = "Sodium, Na",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("b1ca0be3-46ea-4fc4-9ea4-f6b5460eea17"),
                            IsDeleted = false,
                            Name = "Protein",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("180dd2ef-e910-4e7f-a8ab-cb41474d63b0"),
                            IsDeleted = false,
                            Name = "Sugars, total",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("6fb27a04-781e-49d5-a0cb-c25d7c78e7df"),
                            IsDeleted = false,
                            Name = "Sugars, added",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("62fdf1a3-209b-4e74-9ed6-0a2da6df10c0"),
                            IsDeleted = false,
                            Name = "Vitamin D",
                            Unit = "IU"
                        },
                        new
                        {
                            Id = new Guid("35435ac0-5216-469c-abe1-bf47088650ea"),
                            IsDeleted = false,
                            Name = "Sugar Alcohol",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("b263a17b-f130-4689-93fc-417b2306b920"),
                            IsDeleted = false,
                            Name = "Erythritol",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("298693dd-534c-4dcf-8755-f0df1483142e"),
                            IsDeleted = false,
                            Name = "Allulose",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("d68f7f64-0c63-4e0e-aa3a-93f97ec37b14"),
                            IsDeleted = false,
                            Name = "Glycerin",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("cc5582a4-d536-43bb-8ddf-8a4a44cb8c9a"),
                            IsDeleted = false,
                            Name = "Xylitol",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("fdec4a36-3c31-43a8-b96b-22aa746b892d"),
                            IsDeleted = false,
                            Name = "Sorbitol",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("986480b6-e2aa-489e-897c-81926320d4e5"),
                            IsDeleted = false,
                            Name = "Mannitol",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("8a8de098-e4af-4280-8121-172da7fa1653"),
                            IsDeleted = false,
                            Name = "Maltitol",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("195c204c-9a3a-48a9-a4ad-ae9fac6352fa"),
                            IsDeleted = false,
                            Name = "Isomalt",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("e35581d9-2c00-4182-b305-487e76de5204"),
                            IsDeleted = false,
                            Name = "Lactitol",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("35159dfe-2b2e-4859-adb8-7d17c2df8ddf"),
                            IsDeleted = false,
                            Name = "Alanine",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("41e2b244-230a-4b54-b4ec-25db26ee7b4c"),
                            IsDeleted = false,
                            Name = "Alcohol, ethyl",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("8b6a0565-530a-4ae4-8163-201c485620b7"),
                            IsDeleted = false,
                            Name = "Arginine",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("9792947b-cd46-4d9e-b175-4ba09c460d0e"),
                            IsDeleted = false,
                            Name = "Ash",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("db803808-12a1-4e5f-b9dc-a932f5cb6ad6"),
                            IsDeleted = false,
                            Name = "Aspartic acid",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("31a5fc29-515e-4ac6-bc5c-018a5d5460dd"),
                            IsDeleted = false,
                            Name = "Betaine",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("40eb533c-d9b9-420e-b57f-0d3554c3b7ef"),
                            IsDeleted = false,
                            Name = "Caffeine",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("e0ac6740-8942-44b5-931d-fb396631ee40"),
                            IsDeleted = false,
                            Name = "Campesterol",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("5ca3812b-d177-4a3e-8948-e45e1b5f2619"),
                            IsDeleted = false,
                            Name = "Carotene, alpha",
                            Unit = "Âµg"
                        },
                        new
                        {
                            Id = new Guid("78979ca6-2f2e-449d-901f-03dc233b48d4"),
                            IsDeleted = false,
                            Name = "Carotene, beta",
                            Unit = "Âµg"
                        },
                        new
                        {
                            Id = new Guid("09b254c2-6196-4d4a-bfb2-3acd9f5fd9f8"),
                            IsDeleted = false,
                            Name = "Vitamin D3 (cholecalciferol)",
                            Unit = "Âµg"
                        },
                        new
                        {
                            Id = new Guid("13556c89-cc9c-4503-8254-8b519cfed2bb"),
                            IsDeleted = false,
                            Name = "Choline, total",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("32cdc623-d7be-4f06-ab89-f071585d8c1c"),
                            IsDeleted = false,
                            Name = "Cryptoxanthin, beta",
                            Unit = "Âµg"
                        },
                        new
                        {
                            Id = new Guid("4f2fd50b-0840-451d-a991-f174175bd456"),
                            IsDeleted = false,
                            Name = "Copper, Cu",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("01d61688-924e-4a3d-8e39-1caca84e0844"),
                            IsDeleted = false,
                            Name = "Cystine",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("b7ddacdd-33d9-4ffd-bf63-df5bf5a19c23"),
                            IsDeleted = false,
                            Name = "Energy",
                            Unit = "kJ"
                        },
                        new
                        {
                            Id = new Guid("eec306a8-2f88-4d65-8c9b-51cd9dcd2d06"),
                            IsDeleted = false,
                            Name = "Vitamin D2 (ergocalciferol)",
                            Unit = "Âµg"
                        },
                        new
                        {
                            Id = new Guid("f2bc3b0f-5fed-4037-aede-119755394488"),
                            IsDeleted = false,
                            Name = "10:00",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("bc1ba0b5-0ca3-4096-80d9-563eb1e57d97"),
                            IsDeleted = false,
                            Name = "12:00",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("df660f92-ea89-4a90-b7bf-2bf090b84dad"),
                            IsDeleted = false,
                            Name = "13:00",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("9457e52c-76cc-4391-b0e7-28d028e7dc0d"),
                            IsDeleted = false,
                            Name = "14:00",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("f350a432-e749-4a78-b4ef-a85ed7c6533e"),
                            IsDeleted = false,
                            Name = "14:01",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("213bfe86-6c2b-493f-a03f-a1d4fc58b2a0"),
                            IsDeleted = false,
                            Name = "15:00",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("e6fd620d-1255-4cd2-b8e0-10b3f70c38b1"),
                            IsDeleted = false,
                            Name = "15:01",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("cb760f8b-d0cf-4fce-9f9d-0c60167644ca"),
                            IsDeleted = false,
                            Name = "16:00",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("f9fa052e-ff54-40a0-90cf-f34257baf5f2"),
                            IsDeleted = false,
                            Name = "16:1 undifferentiated",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("e5366684-4dd5-4342-91fa-b9e7602ac195"),
                            IsDeleted = false,
                            Name = "16:1 c",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("43e78938-72f8-4234-bc1d-8722678ca10f"),
                            IsDeleted = false,
                            Name = "16:1 t",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("fd0715b9-c807-4106-bd41-82ad6e59ae24"),
                            IsDeleted = false,
                            Name = "17:00",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("34a990a6-ecb2-4693-b6a2-7847dc5fe645"),
                            IsDeleted = false,
                            Name = "17:01",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("7386602a-8239-4c3e-a354-5cc1c665fe66"),
                            IsDeleted = false,
                            Name = "18:00",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("ed279501-bbaf-40de-9d24-3de7e2738803"),
                            IsDeleted = false,
                            Name = "18:1 undifferentiated",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("15c90b30-4bf1-49b5-9149-ef09874044e9"),
                            IsDeleted = false,
                            Name = "18:1 c",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("b5454db4-5500-418e-8baf-4e698e54e715"),
                            IsDeleted = false,
                            Name = "18:1 t",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("a3d19f95-1ae7-4ac5-9cd1-c39adb1d9683"),
                            IsDeleted = false,
                            Name = "18:1-11t (18:1t n-7)",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("e1232069-daf0-444b-9546-8728fd184bca"),
                            IsDeleted = false,
                            Name = "18:2 undifferentiated",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("031d7115-a0b5-4663-8fae-cd2d54d5860f"),
                            IsDeleted = false,
                            Name = "18:2 CLAs",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("3126187d-5a90-4f94-b6a4-2bfa5a65eab7"),
                            IsDeleted = false,
                            Name = "18:2 n-6 c,c",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("c4b978dd-9415-430b-8f96-37152b817447"),
                            IsDeleted = false,
                            Name = "18:2 t,t",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("a7242e2f-9f8b-463c-9060-1aae8b42e887"),
                            IsDeleted = false,
                            Name = "18:3 undifferentiated",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("5a49107d-53b9-412d-8a80-40fe0397fc02"),
                            IsDeleted = false,
                            Name = "18:3 n-3 c,c,c (ALA)",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("96e690a3-c48b-4a78-8f1b-5b456d197ddd"),
                            IsDeleted = false,
                            Name = "18:3 n-6 c,c,c",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("b3a9e840-d577-4527-bd87-288f8c5c9958"),
                            IsDeleted = false,
                            Name = "18:04",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("e18bfbeb-fc4e-4d87-84a2-e28f855db851"),
                            IsDeleted = false,
                            Name = "20:00",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("483fbbce-543e-494f-a71f-757c4683c7c3"),
                            IsDeleted = false,
                            Name = "20:01",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("2c139fd7-981a-4962-a4e5-e380aaa7e1d1"),
                            IsDeleted = false,
                            Name = "20:2 n-6 c,c",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("d226a906-793e-4687-bc45-aed98ddadf7d"),
                            IsDeleted = false,
                            Name = "20:3 undifferentiated",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("3bcaac8e-2033-4dfe-bc77-f3dac53d3adb"),
                            IsDeleted = false,
                            Name = "20:3 n-3",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("7e539245-c33e-4bc9-ab3e-09a3bce96a38"),
                            IsDeleted = false,
                            Name = "20:3 n-6",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("9d4b0a55-5022-4559-ab70-e26b8bd8f533"),
                            IsDeleted = false,
                            Name = "20:4 undifferentiated",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("02868c37-7a2d-40af-bcd5-aa9ba05933c5"),
                            IsDeleted = false,
                            Name = "20:4 n-6",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("711914de-5c17-4eb0-8749-b15912c6a634"),
                            IsDeleted = false,
                            Name = "20:5 n-3 (EPA)",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("880790e8-858f-49a3-ac0d-6816a03f0a8d"),
                            IsDeleted = false,
                            Name = "21:05",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("5bcc8cdf-9ea9-477e-96dc-54e4fa8bfed3"),
                            IsDeleted = false,
                            Name = "22:00",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("a8e864c0-6961-450c-a521-17ba7a39223e"),
                            IsDeleted = false,
                            Name = "22:1 undifferentiated",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("c8378c55-f327-4ff5-aa18-ca439a26b601"),
                            IsDeleted = false,
                            Name = "22:04",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("4a12bfd9-0157-45df-9a10-1f2a6e3811a1"),
                            IsDeleted = false,
                            Name = "22:5 n-3 (DPA)",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("cc9f1df6-c625-4e1b-890b-3804d4a18d21"),
                            IsDeleted = false,
                            Name = "22:6 n-3 (DHA)",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("c91397cf-b878-41e8-aad5-8ebc58af3857"),
                            IsDeleted = false,
                            Name = "24:00:00",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("de113fea-6505-4bbe-9c8e-5f44d974e26d"),
                            IsDeleted = false,
                            Name = "24:1 c",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("1d6e9df3-d6fd-47c0-82ce-57651eb1446a"),
                            IsDeleted = false,
                            Name = "4:00",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("00187677-4fd7-4640-bfa2-64f492ca0d88"),
                            IsDeleted = false,
                            Name = "6:00",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("a1539430-c0d7-4c43-8c5d-4c2135b48e6e"),
                            IsDeleted = false,
                            Name = "8:00",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("2f10c771-cd87-4579-8211-2099dacc598e"),
                            IsDeleted = false,
                            Name = "Fatty acids, total monounsaturated",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("27a06531-a18d-43fa-8cb0-5120f346dfc1"),
                            IsDeleted = false,
                            Name = "Fatty acids, total polyunsaturated",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("f8ad92bd-5123-4741-b0c0-e24f1bcb0888"),
                            IsDeleted = false,
                            Name = "Fatty acids, total trans-monoenoic",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("c59d802f-0cef-410c-87f1-e64b9e68c072"),
                            IsDeleted = false,
                            Name = "Fatty acids, total trans-polyenoic",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("145d0bbc-b6b9-4d6b-acd2-de7a5b382f58"),
                            IsDeleted = false,
                            Name = "Fluoride, F",
                            Unit = "Âµg"
                        },
                        new
                        {
                            Id = new Guid("8c3aca94-7a61-4cad-b97b-87f7ce9b7c26"),
                            IsDeleted = false,
                            Name = "Folate, total",
                            Unit = "Âµg"
                        },
                        new
                        {
                            Id = new Guid("bcdb9b56-8b3e-42ad-815e-2b7ee52ebc27"),
                            IsDeleted = false,
                            Name = "Folic acid",
                            Unit = "Âµg"
                        },
                        new
                        {
                            Id = new Guid("95ce08d0-d496-4f58-a704-9cc8ae00bae6"),
                            IsDeleted = false,
                            Name = "Folate, DFE",
                            Unit = "Âµg"
                        },
                        new
                        {
                            Id = new Guid("c9b361bc-228e-475e-8188-3a4314802351"),
                            IsDeleted = false,
                            Name = "Folate, food",
                            Unit = "Âµg"
                        },
                        new
                        {
                            Id = new Guid("5b1d3996-f0aa-40ce-afab-0535983f3f71"),
                            IsDeleted = false,
                            Name = "Fructose",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("d3198cc8-0dd0-4e72-acf0-256799619627"),
                            IsDeleted = false,
                            Name = "Galactose",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("f79ed152-05d5-4ac9-9b1b-81f4a28d8698"),
                            IsDeleted = false,
                            Name = "Glutamic acid",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("6adcbb0e-f797-4116-877d-2ba61c7ec2c8"),
                            IsDeleted = false,
                            Name = "Glucose (dextrose)",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("657a8a9f-bcf2-48bd-ac29-f1efa7fb0701"),
                            IsDeleted = false,
                            Name = "Glycine",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("4c9ecaa3-4382-4f38-acce-a39833120c7e"),
                            IsDeleted = false,
                            Name = "Histidine",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("71771f9e-ab46-42eb-9538-261a0ae70596"),
                            IsDeleted = false,
                            Name = "Hydroxyproline",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("7b93f187-5386-40b3-a053-aea6548e8eb5"),
                            IsDeleted = false,
                            Name = "Isoleucine",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("3fca3bf0-53ee-4b0a-be1d-25a70d3f5b48"),
                            IsDeleted = false,
                            Name = "Lactose",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("7e581336-4f25-4866-8a8a-e22305a2e9e0"),
                            IsDeleted = false,
                            Name = "Leucine",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("91347054-d516-4cfb-a876-e0293703f636"),
                            IsDeleted = false,
                            Name = "Lutein + zeaxanthin",
                            Unit = "Âµg"
                        },
                        new
                        {
                            Id = new Guid("1143c769-af9d-4183-8907-c46df3d408a6"),
                            IsDeleted = false,
                            Name = "Lycopene",
                            Unit = "Âµg"
                        },
                        new
                        {
                            Id = new Guid("c0b38407-970f-4690-be8c-6b9735eef4fd"),
                            IsDeleted = false,
                            Name = "Lysine",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("ed3485f6-f55a-4cc7-b652-b99d2c82f64b"),
                            IsDeleted = false,
                            Name = "Maltose",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("08e0d1ce-5fb3-4780-a9e7-878a6da46ef4"),
                            IsDeleted = false,
                            Name = "Methionine",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("ff56dd07-244c-453e-aa97-4bcc7760cd79"),
                            IsDeleted = false,
                            Name = "Magnesium, Mg",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("e5b847c7-2bff-46e6-8b2d-147b76bcf043"),
                            IsDeleted = false,
                            Name = "Menaquinone-4",
                            Unit = "Âµg"
                        },
                        new
                        {
                            Id = new Guid("41880e48-1311-41c7-91d5-5eae5bb78e6b"),
                            IsDeleted = false,
                            Name = "Manganese, Mn",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("603875d4-a309-4e39-922c-37218fa1974c"),
                            IsDeleted = false,
                            Name = "Niacin",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("f71f0f17-00da-4a04-8942-c87a005f30c9"),
                            IsDeleted = false,
                            Name = "Vitamin E, added",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("cbfa7cdf-e781-4a8a-8b93-1fca326d7ea6"),
                            IsDeleted = false,
                            Name = "Vitamin B-12, added",
                            Unit = "Âµg"
                        },
                        new
                        {
                            Id = new Guid("8df11934-8272-474d-aedb-92ca6862384b"),
                            IsDeleted = false,
                            Name = "Adjusted Protein",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("c952ffbd-bb70-4bb8-9bb3-5f64cc2a2a5a"),
                            IsDeleted = false,
                            Name = "22:1 t",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("23b00007-ee3a-451d-9c8a-4bc238654f1d"),
                            IsDeleted = false,
                            Name = "22:1 c",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("be1a8d9d-fd1e-4ebc-be95-abe5b1121d3d"),
                            IsDeleted = false,
                            Name = "18:3i",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("bfb22e75-b296-4b79-8fe7-aa1fa049732e"),
                            IsDeleted = false,
                            Name = "18:2 t not further defined",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("09a87134-6acd-433f-9f22-82949ad5878e"),
                            IsDeleted = false,
                            Name = "18:2 i",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("b0b77c9a-79c7-40f1-b7e4-72f34068288e"),
                            IsDeleted = false,
                            Name = "Phosphorus, P",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("dc62a44f-632a-4f56-adb9-51f8d0e6c896"),
                            IsDeleted = false,
                            Name = "Pantothenic acid",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("d5481a82-d13f-4c60-b454-243111f03a49"),
                            IsDeleted = false,
                            Name = "Phenylalanine",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("5e1e5a94-47da-44e4-b1cb-2fec4d6cf81d"),
                            IsDeleted = false,
                            Name = "Phytosterols",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("e1511fd1-3de1-45ed-832a-ee5b4d61f983"),
                            IsDeleted = false,
                            Name = "Proline",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("0e47721a-14b9-4174-a73d-5515cfbd00c6"),
                            IsDeleted = false,
                            Name = "Retinol",
                            Unit = "Âµg"
                        },
                        new
                        {
                            Id = new Guid("3048e404-f677-469c-9aef-ec5ad83158d2"),
                            IsDeleted = false,
                            Name = "Riboflavin",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("1a000942-9789-4ed0-8f68-84c168dc716b"),
                            IsDeleted = false,
                            Name = "Selenium, Se",
                            Unit = "Âµg"
                        },
                        new
                        {
                            Id = new Guid("c6507833-497d-4060-8db1-cbf638f5a803"),
                            IsDeleted = false,
                            Name = "Serine",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("1a5ffa66-c3bc-4989-b863-e3469dcae1de"),
                            IsDeleted = false,
                            Name = "Beta-sitosterol",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("2a91fd10-edd4-406c-b07b-8997dc5ee550"),
                            IsDeleted = false,
                            Name = "Starch",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("299364c5-1ca0-48aa-964f-149c39c75763"),
                            IsDeleted = false,
                            Name = "Stigmasterol",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("8ef2c8a9-c00e-40c2-89f1-111a41c6c174"),
                            IsDeleted = false,
                            Name = "Sucrose",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("7e89fa22-068b-4439-8cf6-284fc943f4fe"),
                            IsDeleted = false,
                            Name = "Theobromine",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("b9af5c83-26ff-49ca-9057-6cb05da209b4"),
                            IsDeleted = false,
                            Name = "Thiamin",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("3d6f2328-3da1-4f43-aa43-0bd4ff9356a8"),
                            IsDeleted = false,
                            Name = "Threonine",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("c53d74db-b6d0-4d04-a61e-cb87c3bdebb4"),
                            IsDeleted = false,
                            Name = "Vitamin E (alpha-tocopherol)",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("5fa842ab-7781-4bf1-8065-8debfaa5b811"),
                            IsDeleted = false,
                            Name = "Tocopherol, beta",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("fb89788e-4fa2-4e4a-b211-74470af49b65"),
                            IsDeleted = false,
                            Name = "Tocopherol, delta",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("3f8bd51b-531f-480c-a8d8-9172d721088b"),
                            IsDeleted = false,
                            Name = "Tocopherol, gamma",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("eebf87fe-53a1-482c-9ec2-01e084dd5d74"),
                            IsDeleted = false,
                            Name = "Tryptophan",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("0e1d39c8-500e-468a-8799-7497753a9186"),
                            IsDeleted = false,
                            Name = "Tyrosine",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("d17dd16e-4313-4fbe-b754-236d6844122f"),
                            IsDeleted = false,
                            Name = "Valine",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("f234bbd7-1fe1-4ca9-a0ba-4f58c6a26e7c"),
                            IsDeleted = false,
                            Name = "Vitamin A, IU",
                            Unit = "IU"
                        },
                        new
                        {
                            Id = new Guid("6b597ae6-0dd2-4c15-91c7-d96be4767274"),
                            IsDeleted = false,
                            Name = "Vitamin A, RAE",
                            Unit = "Âµg"
                        },
                        new
                        {
                            Id = new Guid("cd365c75-7129-4748-8af0-a8cbd505a0ec"),
                            IsDeleted = false,
                            Name = "Vitamin B-12",
                            Unit = "Âµg"
                        },
                        new
                        {
                            Id = new Guid("eef6bebc-dbc5-4c85-b668-8c05bb26a3e8"),
                            IsDeleted = false,
                            Name = "Vitamin B-6",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("88a4ff58-bd22-4e32-b169-c6d6ef67d2ee"),
                            IsDeleted = false,
                            Name = "Vitamin C, total ascorbic acid",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("aa2f287c-cc85-4e96-8c6a-e1ca4e5ba4e6"),
                            IsDeleted = false,
                            Name = "Vitamin D (D2 + D3)",
                            Unit = "Âµg"
                        },
                        new
                        {
                            Id = new Guid("c79dfa14-77c6-483f-a7f0-26e442b9df28"),
                            IsDeleted = false,
                            Name = "Vitamin K (phylloquinone)",
                            Unit = "Âµg"
                        },
                        new
                        {
                            Id = new Guid("d4d13698-7c99-4560-972f-8df8d1bf50b8"),
                            IsDeleted = false,
                            Name = "Dihydrophylloquinone",
                            Unit = "Âµg"
                        },
                        new
                        {
                            Id = new Guid("0a8f83a8-225b-4332-97da-1b39ff2eaf5d"),
                            IsDeleted = false,
                            Name = "Water",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("cbf7cd31-2708-4956-b1c7-d12dcd691208"),
                            IsDeleted = false,
                            Name = "Zinc, Zn",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("f7362078-3adf-4cfd-accf-7ec71d59c353"),
                            IsDeleted = false,
                            Name = "Tocotrienol, alpha",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("5b52676a-741b-49d8-a842-e8b63fcae889"),
                            IsDeleted = false,
                            Name = "Tocotrienol, beta",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("c050ffb9-f639-4dd6-b692-108a5ac19878"),
                            IsDeleted = false,
                            Name = "Tocotrienol, gamma",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("833d08a9-8775-4187-84d3-278efe75a5f1"),
                            IsDeleted = false,
                            Name = "Tocotrienol,delta",
                            Unit = "mg"
                        });
                });

            modelBuilder.Entity("FoodCatalog.Api.Models.Domain.Food", b =>
                {
                    b.HasOne("FoodCatalog.Api.Models.Domain.Meal", null)
                        .WithMany("Foods")
                        .HasForeignKey("MealId");
                });

            modelBuilder.Entity("FoodCatalog.Api.Models.Domain.FoodMeal", b =>
                {
                    b.HasOne("FoodCatalog.Api.Models.Domain.Measure", "Measure")
                        .WithMany()
                        .HasForeignKey("MeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Measure");
                });

            modelBuilder.Entity("FoodCatalog.Api.Models.Domain.FoodNutrientIn100g", b =>
                {
                    b.HasOne("FoodCatalog.Api.Models.Domain.Food", "Food")
                        .WithMany("FoodNutrients")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodCatalog.Api.Models.Domain.Nutrient", "Nutrient")
                        .WithMany()
                        .HasForeignKey("NutrientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Nutrient");
                });

            modelBuilder.Entity("FoodCatalog.Api.Models.Domain.Measure", b =>
                {
                    b.HasOne("FoodCatalog.Api.Models.Domain.Food", "Food")
                        .WithMany("Measures")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");
                });

            modelBuilder.Entity("FoodCatalog.Api.Models.Domain.Food", b =>
                {
                    b.Navigation("FoodNutrients");

                    b.Navigation("Measures");
                });

            modelBuilder.Entity("FoodCatalog.Api.Models.Domain.Meal", b =>
                {
                    b.Navigation("Foods");
                });
#pragma warning restore 612, 618
        }
    }
}
