// <auto-generated />
using System;
using FoodRecords.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodRecords.Api.Migrations
{
    [DbContext(typeof(FoodRecordsDbContext))]
    [Migration("20250528124419_EditRecipeRecords")]
    partial class EditRecipeRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoodRecords.Api.Models.Domain.FoodPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FoodMeasureId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<string>("RecurringDaysRaw")
                        .HasColumnType("text");

                    b.Property<bool>("RequireConfirmationOnAdd")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("FoodPlans");
                });

            modelBuilder.Entity("FoodRecords.Api.Models.Domain.FoodRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<DateTime>("DateEaten")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FoodMeasureId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FoodRecords");
                });

            modelBuilder.Entity("FoodRecords.Api.Models.Domain.IngredientSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<long>("FoodMeasureId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RecipeRecordId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RecipeRecordId");

                    b.ToTable("IngredientSnapshot");
                });

            modelBuilder.Entity("FoodRecords.Api.Models.Domain.RecipeRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateEaten")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RecipeRecords");
                });

            modelBuilder.Entity("FoodRecords.Api.Models.Domain.IngredientSnapshot", b =>
                {
                    b.HasOne("FoodRecords.Api.Models.Domain.RecipeRecord", null)
                        .WithMany("IngredientSnapshots")
                        .HasForeignKey("RecipeRecordId");
                });

            modelBuilder.Entity("FoodRecords.Api.Models.Domain.RecipeRecord", b =>
                {
                    b.Navigation("IngredientSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
