// <auto-generated />
using System;
using Auth.Persistance.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Auth.Persistance.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20250615194657_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Auth.Domain.Entities.NutrientTracking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long>("NutrientId")
                        .HasColumnType("bigint");

                    b.Property<float>("TargetAmount")
                        .HasColumnType("real");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NutrientTrackings");

                    b.HasData(
                        new
                        {
                            Id = 162L,
                            IsActive = false,
                            NutrientId = 301L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 163L,
                            IsActive = false,
                            NutrientId = 205L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 164L,
                            IsActive = false,
                            NutrientId = 601L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 165L,
                            IsActive = false,
                            NutrientId = 208L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 166L,
                            IsActive = false,
                            NutrientId = 606L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 167L,
                            IsActive = false,
                            NutrientId = 204L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 168L,
                            IsActive = false,
                            NutrientId = 605L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 169L,
                            IsActive = false,
                            NutrientId = 303L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 170L,
                            IsActive = false,
                            NutrientId = 291L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 171L,
                            IsActive = false,
                            NutrientId = 306L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 172L,
                            IsActive = false,
                            NutrientId = 307L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 173L,
                            IsActive = false,
                            NutrientId = 203L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 174L,
                            IsActive = false,
                            NutrientId = 269L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 175L,
                            IsActive = false,
                            NutrientId = 539L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 176L,
                            IsActive = false,
                            NutrientId = 324L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 177L,
                            IsActive = false,
                            NutrientId = 299L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 178L,
                            IsActive = false,
                            NutrientId = 1001L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 179L,
                            IsActive = false,
                            NutrientId = 1006L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 180L,
                            IsActive = false,
                            NutrientId = 1002L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 181L,
                            IsActive = false,
                            NutrientId = 290L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 182L,
                            IsActive = false,
                            NutrientId = 261L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 183L,
                            IsActive = false,
                            NutrientId = 260L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 184L,
                            IsActive = false,
                            NutrientId = 1003L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 185L,
                            IsActive = false,
                            NutrientId = 1004L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 186L,
                            IsActive = false,
                            NutrientId = 1005L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 187L,
                            IsActive = false,
                            NutrientId = 513L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 188L,
                            IsActive = false,
                            NutrientId = 221L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 189L,
                            IsActive = false,
                            NutrientId = 511L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 190L,
                            IsActive = false,
                            NutrientId = 207L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 191L,
                            IsActive = false,
                            NutrientId = 514L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 192L,
                            IsActive = false,
                            NutrientId = 454L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 193L,
                            IsActive = false,
                            NutrientId = 262L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 194L,
                            IsActive = false,
                            NutrientId = 639L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 195L,
                            IsActive = false,
                            NutrientId = 322L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 196L,
                            IsActive = false,
                            NutrientId = 321L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 197L,
                            IsActive = false,
                            NutrientId = 326L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 198L,
                            IsActive = false,
                            NutrientId = 421L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 199L,
                            IsActive = false,
                            NutrientId = 334L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 200L,
                            IsActive = false,
                            NutrientId = 312L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 201L,
                            IsActive = false,
                            NutrientId = 507L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 202L,
                            IsActive = false,
                            NutrientId = 268L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 203L,
                            IsActive = false,
                            NutrientId = 325L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 204L,
                            IsActive = false,
                            NutrientId = 610L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 205L,
                            IsActive = false,
                            NutrientId = 611L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 206L,
                            IsActive = false,
                            NutrientId = 696L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 207L,
                            IsActive = false,
                            NutrientId = 612L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 208L,
                            IsActive = false,
                            NutrientId = 625L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 209L,
                            IsActive = false,
                            NutrientId = 652L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 210L,
                            IsActive = false,
                            NutrientId = 697L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 211L,
                            IsActive = false,
                            NutrientId = 613L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 212L,
                            IsActive = false,
                            NutrientId = 626L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 213L,
                            IsActive = false,
                            NutrientId = 673L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 214L,
                            IsActive = false,
                            NutrientId = 662L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 215L,
                            IsActive = false,
                            NutrientId = 653L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 216L,
                            IsActive = false,
                            NutrientId = 687L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 217L,
                            IsActive = false,
                            NutrientId = 614L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 218L,
                            IsActive = false,
                            NutrientId = 617L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 219L,
                            IsActive = false,
                            NutrientId = 674L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 220L,
                            IsActive = false,
                            NutrientId = 663L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 221L,
                            IsActive = false,
                            NutrientId = 859L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 222L,
                            IsActive = false,
                            NutrientId = 618L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 223L,
                            IsActive = false,
                            NutrientId = 670L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 224L,
                            IsActive = false,
                            NutrientId = 675L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 225L,
                            IsActive = false,
                            NutrientId = 669L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 226L,
                            IsActive = false,
                            NutrientId = 619L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 227L,
                            IsActive = false,
                            NutrientId = 851L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 228L,
                            IsActive = false,
                            NutrientId = 685L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 229L,
                            IsActive = false,
                            NutrientId = 627L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 230L,
                            IsActive = false,
                            NutrientId = 615L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 231L,
                            IsActive = false,
                            NutrientId = 628L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 232L,
                            IsActive = false,
                            NutrientId = 672L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 233L,
                            IsActive = false,
                            NutrientId = 689L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 234L,
                            IsActive = false,
                            NutrientId = 852L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 235L,
                            IsActive = false,
                            NutrientId = 853L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 236L,
                            IsActive = false,
                            NutrientId = 620L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 237L,
                            IsActive = false,
                            NutrientId = 855L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 238L,
                            IsActive = false,
                            NutrientId = 629L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 239L,
                            IsActive = false,
                            NutrientId = 857L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 240L,
                            IsActive = false,
                            NutrientId = 624L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 241L,
                            IsActive = false,
                            NutrientId = 630L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 242L,
                            IsActive = false,
                            NutrientId = 858L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 243L,
                            IsActive = false,
                            NutrientId = 631L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 244L,
                            IsActive = false,
                            NutrientId = 621L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 245L,
                            IsActive = false,
                            NutrientId = 654L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 246L,
                            IsActive = false,
                            NutrientId = 671L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 247L,
                            IsActive = false,
                            NutrientId = 607L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 248L,
                            IsActive = false,
                            NutrientId = 608L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 249L,
                            IsActive = false,
                            NutrientId = 609L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 250L,
                            IsActive = false,
                            NutrientId = 645L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 251L,
                            IsActive = false,
                            NutrientId = 646L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 252L,
                            IsActive = false,
                            NutrientId = 693L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 253L,
                            IsActive = false,
                            NutrientId = 695L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 254L,
                            IsActive = false,
                            NutrientId = 313L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 255L,
                            IsActive = false,
                            NutrientId = 417L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 256L,
                            IsActive = false,
                            NutrientId = 431L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 257L,
                            IsActive = false,
                            NutrientId = 435L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 258L,
                            IsActive = false,
                            NutrientId = 432L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 259L,
                            IsActive = false,
                            NutrientId = 212L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 260L,
                            IsActive = false,
                            NutrientId = 287L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 261L,
                            IsActive = false,
                            NutrientId = 515L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 262L,
                            IsActive = false,
                            NutrientId = 211L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 263L,
                            IsActive = false,
                            NutrientId = 516L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 264L,
                            IsActive = false,
                            NutrientId = 512L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 265L,
                            IsActive = false,
                            NutrientId = 521L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 266L,
                            IsActive = false,
                            NutrientId = 503L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 267L,
                            IsActive = false,
                            NutrientId = 213L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 268L,
                            IsActive = false,
                            NutrientId = 504L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 269L,
                            IsActive = false,
                            NutrientId = 338L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 270L,
                            IsActive = false,
                            NutrientId = 337L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 271L,
                            IsActive = false,
                            NutrientId = 505L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 272L,
                            IsActive = false,
                            NutrientId = 214L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 273L,
                            IsActive = false,
                            NutrientId = 506L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 274L,
                            IsActive = false,
                            NutrientId = 304L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 275L,
                            IsActive = false,
                            NutrientId = 428L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 276L,
                            IsActive = false,
                            NutrientId = 315L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 277L,
                            IsActive = false,
                            NutrientId = 406L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 278L,
                            IsActive = false,
                            NutrientId = 573L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 279L,
                            IsActive = false,
                            NutrientId = 578L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 280L,
                            IsActive = false,
                            NutrientId = 257L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 281L,
                            IsActive = false,
                            NutrientId = 664L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 282L,
                            IsActive = false,
                            NutrientId = 676L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 283L,
                            IsActive = false,
                            NutrientId = 856L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 284L,
                            IsActive = false,
                            NutrientId = 665L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 285L,
                            IsActive = false,
                            NutrientId = 666L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 286L,
                            IsActive = false,
                            NutrientId = 305L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 287L,
                            IsActive = false,
                            NutrientId = 410L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 288L,
                            IsActive = false,
                            NutrientId = 508L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 289L,
                            IsActive = false,
                            NutrientId = 636L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 290L,
                            IsActive = false,
                            NutrientId = 517L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 291L,
                            IsActive = false,
                            NutrientId = 319L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 292L,
                            IsActive = false,
                            NutrientId = 405L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 293L,
                            IsActive = false,
                            NutrientId = 317L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 294L,
                            IsActive = false,
                            NutrientId = 518L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 295L,
                            IsActive = false,
                            NutrientId = 641L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 296L,
                            IsActive = false,
                            NutrientId = 209L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 297L,
                            IsActive = false,
                            NutrientId = 638L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 298L,
                            IsActive = false,
                            NutrientId = 210L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 299L,
                            IsActive = false,
                            NutrientId = 263L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 300L,
                            IsActive = false,
                            NutrientId = 404L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 301L,
                            IsActive = false,
                            NutrientId = 502L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 302L,
                            IsActive = false,
                            NutrientId = 323L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 303L,
                            IsActive = false,
                            NutrientId = 341L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 304L,
                            IsActive = false,
                            NutrientId = 343L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 305L,
                            IsActive = false,
                            NutrientId = 342L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 306L,
                            IsActive = false,
                            NutrientId = 501L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 307L,
                            IsActive = false,
                            NutrientId = 509L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 308L,
                            IsActive = false,
                            NutrientId = 510L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 309L,
                            IsActive = false,
                            NutrientId = 318L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 310L,
                            IsActive = false,
                            NutrientId = 320L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 311L,
                            IsActive = false,
                            NutrientId = 418L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 312L,
                            IsActive = false,
                            NutrientId = 415L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 313L,
                            IsActive = false,
                            NutrientId = 401L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 314L,
                            IsActive = false,
                            NutrientId = 328L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 315L,
                            IsActive = false,
                            NutrientId = 430L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 316L,
                            IsActive = false,
                            NutrientId = 429L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 317L,
                            IsActive = false,
                            NutrientId = 255L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 318L,
                            IsActive = false,
                            NutrientId = 309L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 319L,
                            IsActive = false,
                            NutrientId = 344L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 320L,
                            IsActive = false,
                            NutrientId = 345L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 321L,
                            IsActive = false,
                            NutrientId = 346L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        },
                        new
                        {
                            Id = 322L,
                            IsActive = false,
                            NutrientId = 347L,
                            TargetAmount = 0f,
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "9d75c886-0a61-40a1-8740-aaf027b8572f",
                            ConcurrencyStamp = "9d75c886-0a61-40a1-8740-aaf027b8572f",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "51d825fc-b536-4568-9679-7e8eac698ebe",
                            ConcurrencyStamp = "51d825fc-b536-4568-9679-7e8eac698ebe",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4bba7b4c-46be-4e5a-99c3-af68d35ef9b0",
                            Email = "coolmailedu@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "COOLMAILEDU@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEJzHPFuc2hfuHryBcAqo1JOjnmRC4PIV9Z9MamzH+u5ZcxgOOdIj+m4L8BEmyXJa/g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "85235144-51ac-480e-bb5f-6c068813bfcd",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "3c8b0d12-13e9-4f42-85a4-5d3ce1e7e34f",
                            RoleId = "9d75c886-0a61-40a1-8740-aaf027b8572f"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
