version: '3.4'

services:
  postgres:
    image: postgres
  foodcatalogredis:
    image: foodcatalogredis
  qdrant:
    image: qdrant
  rabbitmq:
    image: rabbitmq
  auth.api:
    image: ${DOCKER_REGISTRY-}authapi
    build:
      context: .
      dockerfile: Services/Auth/Auth.API/Dockerfile
    depends_on:
      - postgres

  foodcatalog.api:
    image: ${DOCKER_REGISTRY-}foodcatalogapi
    build:
      context: .
      dockerfile: Services/FoodCatalog/FoodCatalog.Api/Dockerfile
    depends_on:
      - postgres
      - foodcatalogredis 
      - rabbitmq
  foodrecords.api:
    image: ${DOCKER_REGISTRY-}foodrecordsapi
    build:
      context: .
      dockerfile: Services/FoodRecords/FoodRecords.Api/Dockerfile
    depends_on:
      - postgres
      - rabbitmq

  recommendationservice.api:
    image: ${DOCKER_REGISTRY-}recommendationserviceapi
    build:
      context: .
      dockerfile: Services/Recommendation/RecommendationService.Api/Dockerfile
    depends_on:
      - foodcatalogredis 
      - qdrant
      - postgres
 

#  gateway.api:
#    image: ${DOCKER_REGISTRY-}gatewayapi
#    build:
#      context: .
#      dockerfile: Gateway.API/Dockerfile
#    depends_on:
#      - recommendationservice.api
#      - foodrecords.api
#      - foodcatalog.api
#      - auth.api

volumes:
  redis_data:
  qdrant_data:
  postgres_recipes:
