version: '3.4'

services:
  authdb:
    image: authdb

  foodcatalogdb:
    image: foodcatalogdb

  recipedb:
    image: recipedb

  foodcatalogredis:
    image: foodcatalogredis

  qdrant:
    image: qdrant

  foodrecordsdb:
    image: foodrecordsdb

  messagebroker:
    image: rabbitmq:management

  auth.api:
    image: ${DOCKER_REGISTRY-}authapi
    build:
      context: .
      dockerfile: Services/Auth/Auth.API/Dockerfile
    depends_on:
      - authdb

  foodcatalog.api:
    image: ${DOCKER_REGISTRY-}foodcatalogapi
    build:
      context: .
      dockerfile: Services/FoodCatalog/FoodCatalog.Api/Dockerfile
    depends_on:
      - foodcatalogdb
      - foodcatalogredis 
      - messagebroker


  foodrecords.api:
    image: ${DOCKER_REGISTRY-}foodrecordsapi
    build:
      context: .
      dockerfile: Services/FoodRecords/FoodRecords.Api/Dockerfile
    depends_on:
      - foodrecordsdb

  recommendationservice.api:
    image: ${DOCKER_REGISTRY-}recommendationserviceapi
    build:
      context: .
      dockerfile: Services/Recommendation/RecommendationService.Api/Dockerfile
    depends_on:
      - foodcatalogredis 
      - qdrant
      - recipedb
      - messagebroker


  gateway.api:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: Gateway.API/Dockerfile
    depends_on:
      - recommendationservice.api
      - foodrecords.api
      - foodcatalog.api
      - auth.api


volumes:
  sql_data:
  postgres_foodcatalog:
  redis_data:
  postgres_foodrecords:
  qdrant_data:
  postgres_recipes:

