version: '3.4'

services:
  authdb:
    image: authdb
  foodcatalogdb:
    image: foodcatalogdb
  foodcatalogredis:
    image: foodcatalogredis
  qdrant:
    image: qdrant
  recipedb:
    image: recipedb
  foodrecordsdb:
    image: foodrecordsdb

  auth.api:
    image: ${DOCKER_REGISTRY-}authapi
    build:
      context: .
      dockerfile: Services/Auth/Auth.API/Dockerfile
    depends_on:
        - authdb

  foodcatalog.api:
    image: ${DOCKER_REGISTRY-}foodcatalogapi
    build:
      context: .
      dockerfile: Services/FoodCatalog/FoodCatalog.Api/Dockerfile
    depends_on:
        - foodcatalogdb
        - foodcatalogredis 
  foodrecords.api:
    image: ${DOCKER_REGISTRY-}foodrecordsapi
    build:
      context: .
      dockerfile: Services/FoodRecords/FoodRecords.Api/Dockerfile
    depends_on:
      - foodrecordsdb

  recommendationservice.api:
    image: ${DOCKER_REGISTRY-}recommendationserviceapi
    build:
      context: .
      dockerfile: Services/Recommendation/RecommendationService.Api/Dockerfile
    depends_on:
        - foodcatalogredis 
        - qdrant

volumes:
  sql_data:
  postgres_foodcatalog:
  redis_data:
  postgres_foodrecords:
  qdrant_data:
  postgres_recipes:

